### ISSUE TITLE
Using your overlays in my OSS emulator?

### ISSUE THREAD

**Issue by amaiorano** [libretro/overlay-borders#6]
Hello,

I wanted to ask about whether it was alright for me to distribute these wonderful overlays with my own open-source Vectrex emulator ([here](https://github.com/amaiorano/vectrexy)). I don't plan to actually commit them to my repo, just to package them with the binary. I know it's MIT licensed, but I'd like to know if you have any preference for attribution?

Cheers,

Antonio Maiorano

**Comment by hizzlekizzle** [comment]
For the Vectrex ones, I think you'll be fine just mentioning the people from the cfgs:
THK-Hyperspin
Gigapig-Hyperspin
Nosh01-GitHub

**Comment by amaiorano** [comment]
Sounds great, I'll do exactly that. If there's nothing else, feel free to close this issue. Thank you!
